### ISSUE TITLE
Abandoned Kernel 

### ISSUE THREAD

**Issue by circutrider21** [sigma-os/Sigma#11]
I was just wondering whether you would go back to work on this kernel. You could for example port it to aarch64 or add coreutils/weston/others to your userland. Anyways, this kernel is quite cool and its a shame to see it go to rest.

Best Wishes,
Uiop Pilon

**Comment by shreyaslad** [comment]
I agree, you should port this to both arm and risc-v, with emphasis on apple silicon

**Comment by thomtl** [comment]
Sigma has been dead for quite a while, primarily caused due to a bug that proved undebuggable, even over multiple months. And although I've moved on to other projects, you're welcome to fork it, as far as the license permits.
