### ISSUE TITLE
Dashlane Integration

### ISSUE THREAD

**Issue by steve-soundings** [sigma-os/Sigma#12]
#suggestion #password_tool #Dashlane

Turns out this is more important to my workflow than I’d ever realized. I’m using the beta version of the SigmaOS Dashlane integration, and it’s … ok. The autofill feature I use in other browsers is painful not to have. Honestly, this is the only issue that’s keeping me from moving everything off Brave and into Sigma.

**Comment by StaticSaga** [comment]
Sigma browser when?

**Comment by circutrider21** [comment]
Wait WHAT DID HE JUST SAY?

**Comment by circutrider21** [comment]
SigmaOS Dashlane Integration???
